/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import static GUI.pInicio.ContenedorInicio;
import static GUI.pInicio.btnPagAnterior;
import static GUI.pInicio.btnPagFinal;
import static GUI.pInicio.btnPagInicio;
import static GUI.pInicio.btnPagSiguiente;
import static GUI.pInicio.etiEstadoGuardar;
import java.awt.Color;
import java.awt.GridLayout;

/**
 *
 * @author angel
 */
public class pIniciemos extends javax.swing.JPanel {

    /**
     * Creates new form pIniciemos
     */
    public pIniciemos() {
        initComponents();
        ValoresIniciales();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenedor = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Centro = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnPerfil = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        btnEntrada = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        btnSalida = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        btnAlumnos = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();

        setLayout(new java.awt.GridLayout(1, 0));

        Contenedor.setBackground(new java.awt.Color(244, 244, 244));

        jPanel1.setBackground(new java.awt.Color(249, 249, 249));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setBackground(new java.awt.Color(24, 160, 221));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(24, 160, 221));
        jLabel1.setText("<html>\n<p></p>\n<p></p>\nBienvenido\n<p></p>\n<p></p>\n<p></p>\n<html>");
        jPanel1.add(jLabel1, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.BorderLayout());

        Centro.setOpaque(false);
        Centro.setLayout(new java.awt.GridLayout(2, 2));

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        btnPerfil.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/user(1).png"))); // NOI18N
        btnPerfil.setText(" Ver mi pefil");
        btnPerfil.setToolTipText("");
        btnPerfil.setContentAreaFilled(false);
        btnPerfil.setFocusPainted(false);
        btnPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPerfilMouseClicked(evt);
            }
        });
        jPanel4.add(btnPerfil);

        Centro.add(jPanel4);

        jPanel9.setOpaque(false);
        jPanel9.setLayout(new java.awt.GridLayout(1, 0));

        btnEntrada.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/logina.png"))); // NOI18N
        btnEntrada.setText(" Registrar Entrada");
        btnEntrada.setContentAreaFilled(false);
        btnEntrada.setFocusPainted(false);
        btnEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradaActionPerformed(evt);
            }
        });
        jPanel9.add(btnEntrada);

        Centro.add(jPanel9);

        jPanel10.setOpaque(false);
        jPanel10.setLayout(new java.awt.GridLayout(1, 0));

        btnSalida.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/salida.png"))); // NOI18N
        btnSalida.setText(" Registrar Salida");
        btnSalida.setContentAreaFilled(false);
        btnSalida.setFocusPainted(false);
        btnSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidaActionPerformed(evt);
            }
        });
        jPanel10.add(btnSalida);

        Centro.add(jPanel10);

        jPanel11.setOpaque(false);
        jPanel11.setLayout(new java.awt.GridLayout(1, 0));

        btnAlumnos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAlumnos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/pasar.png"))); // NOI18N
        btnAlumnos.setText(" Ir a alumnos");
        btnAlumnos.setContentAreaFilled(false);
        btnAlumnos.setFocusPainted(false);
        btnAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlumnosActionPerformed(evt);
            }
        });
        jPanel11.add(btnAlumnos);

        Centro.add(jPanel11);

        jPanel3.add(Centro, java.awt.BorderLayout.CENTER);

        jPanel5.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel2.setText("<HTML> <P></P> ¿Qué quieres hacer? <P></P> <P></P> <HTML>");
        jPanel5.add(jLabel2);

        jPanel3.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel6.setOpaque(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 959, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 61, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        jPanel7.setOpaque(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 227, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel7, java.awt.BorderLayout.LINE_END);

        jPanel8.setOpaque(false);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 227, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel8, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout ContenedorLayout = new javax.swing.GroupLayout(Contenedor);
        Contenedor.setLayout(ContenedorLayout);
        ContenedorLayout.setHorizontalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ContenedorLayout.setVerticalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(Contenedor);
    }// </editor-fold>//GEN-END:initComponents
    
    void ValoresIniciales(){
        /*Barra*/
        btnPagInicio.setVisible(false);
        btnPagAnterior.setVisible(false);
        btnPagSiguiente.setVisible(false);
        btnPagFinal.setVisible(false);
        etiEstadoGuardar.setText("");
        etiEstadoGuardar.setForeground(new Color(51,51,51));
    }
    
    private void btnPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerfilMouseClicked
        pInicio.PanelSelectReset(pInicio.User);
        pUsuario usuario = new pUsuario();
        ContenedorInicio.removeAll();
        ContenedorInicio.add(usuario,GridLayout.class);
        ContenedorInicio.revalidate();
        ContenedorInicio.repaint();
    }//GEN-LAST:event_btnPerfilMouseClicked

    private void btnEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradaActionPerformed
        pInicio.PanelSelectReset(pInicio.btnEntrada);
        pEntrada usuario = new pEntrada();
        ContenedorInicio.removeAll();
        ContenedorInicio.add(usuario,GridLayout.class);
        ContenedorInicio.revalidate();
        ContenedorInicio.repaint();
    }//GEN-LAST:event_btnEntradaActionPerformed

    private void btnSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidaActionPerformed
        pInicio.PanelSelectReset(pInicio.btnSalida);
        pSalida usuario = new pSalida();
        ContenedorInicio.removeAll();
        ContenedorInicio.add(usuario,GridLayout.class);
        ContenedorInicio.revalidate();
        ContenedorInicio.repaint();
    }//GEN-LAST:event_btnSalidaActionPerformed

    private void btnAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlumnosActionPerformed
        pInicio.PanelSelectReset(pInicio.btnAlumnos);
        pAlumnos usuario = new pAlumnos();
        ContenedorInicio.removeAll();
        ContenedorInicio.add(usuario,GridLayout.class);
        ContenedorInicio.revalidate();
        ContenedorInicio.repaint();
    }//GEN-LAST:event_btnAlumnosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Centro;
    private javax.swing.JPanel Contenedor;
    private javax.swing.JButton btnAlumnos;
    private javax.swing.JButton btnEntrada;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JButton btnSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
